
- alias: 'Leave Home notification'
  trigger:
    platform: zone
    event: leave
    zone: zone.home
    entity_id: device_tracker.anders_anders
  action:
    service: notify.slack
    data:
      message: 'Anders left the house'
